title: ВКР
syntax: XML
supportedLanguages: []
properties:
  - name: Статус
    type: Enum
    style: blue-green
    icon: file-warning
    values:
      - Реализовано
      - Запланировано
      - В работе
      - Не будет реализовано
  - name: Текст
    type: Text
    style: black
  - name: бт1
    type: BlockMd
  - name: бт2
    type: BlockMd
